export const links = [
  { title: "О посёлке", href: "#uniq", offset: -105, offsetmob: -105 },
  { title: "Наши проекты", href: "#projects", offset: 140, offsetmob: -40 },
  { title: "Генплан", href: "#genplan", offset: -115, offsetmob: -115 },
  { title: "Галерея", href: "#galary", offset: -105, offsetmob: -105 },
  { title: "Покупка", href: "#howtobuy", offset: 140, offsetmob: 20 },
  { title: "Контакты", href: "#contacts", offset: -125, offsetmob: -50 },
];

export const uniqCards = [
  {
    icon: "/snow_man.svg",
    title: "Территория",
    bold: "Ярвино находится в 850 м по прямой от Финского залива, на второй береговой линии.",
    desc: "<div><br>Берег залива станет вашим любимым местом для прогулок и отдыха. До ближайшего общественного пляжа можно добраться на автомобиле менее чем за 5 минут.</div><div><br>Посёлок окружен хвойным лесом, на границе протекает Майский ручей. Ярвино находится на возвышении, почва сухая и песчаная. Экология района благоприятна для земледелия, раньше здесь располагались поля колхоза.</div>",
    img: "/card_u_1.png",
    imgMob: "/mob_pic_1.png",
    list: [],
  },
  {
    list: [],
    bold: "Поселок Ярвино находится в в 70 км от КАД в Выборгском районе Ленинградской области.",
    icon: "/house.svg",
    title: "Расположение",
    desc: "<div><br>Путь из города в ваш дом будет легким и приятным. Скоростной участок ЗСД, живописное Зеленогорское шоссе, идущее вдоль залива Приморское шоссе. Уже в дороге вы начнете отдыхать от шума и суеты мегаполиса.</div>",
    img: "/card_u_2.png",
    imgMob: "/mob_pic_2.png",
  },
  {
    list: [],
    bold: "Въезд в посёлок расположен в 200 м от Приморского шоссе. На территории посёлка проложены качественные широкие дороги (до 7 метров в ширину) с твёрдым покрытием.",
    icon: "/dots.svg",
    title: "Инфраструктура",
    desc: "<div><br>На территории посёлка отведено полгектара территории под озеленение на землях общего пользования, а также продовольственный магазин, площадка для баскетбола, мини-футбола, тренажёрная и детская площадки.</div><div><br>Здание администрации и офис продаж имеет удобное расположение на территории въездной группы.</div>",
    img: "/card_u_3.png",
    imgMob: "/mob_pic_3.png",
  },
  {
    icon: "/wind.svg",
    bold: "Поселок оснащен всеми необходимыми коммуникациями для жизни за городом круглый год. ",
    title: "Коммуникации",
    desc: "Ко всем участкам подведены:",
    list: [
      "<b>Электричество</b> мощностью 10 кВт (можно увеличить до 15 кВт).",
      "Точка подключения к центральному <b>газопроводу</b>.",
      "<b>Водопровод</b> из собственной скважины поселка.",
      "<b>Локальная система канализации</b> с септиками устанавливается владельцами земельных участков отдельно.",
    ],
    img: "/card_u_4.png",
    imgMob: "/mob_pic_4.png",
  },
];
export const howToBuyCards = [
  {
    icon: "/choose.svg",
    title: "Выберите участок",
    desc: "Изучите интерактивный план поселка и определитесь с участком, который отвечает вашим желаниям.",
    imgNum: "/one.png",
  },
  {
    icon: "/pen.svg",
    title: "Запишитесь на просмотр",
    desc: "Обратитесь к нам по телефону, мессенджеру Whatsapp или Telegram, электронной почте или в форме обратной связи. Менеджер предложит вам подходящее время визита в Ярвино.",
    imgNum: "/two.png",
  },
  {
    icon: "/star.svg",
    title: "Посетите Ярвино",
    desc: "Насладитесь природой и экологией поселка, оцените транспортную доступность и близость к заливу и выберите участок мечты.",
    imgNum: "/three.png",
  },
  {
    icon: "/rub.svg",
    title: "Оформите покупку",
    desc: "Приобретите участок в собственность — мы помогаем клиентам с оформлением документов и регистрацией сделки в Росреестре.",
    imgNum: "/four.png",
  },
];

export const textC = [
  "Аэросъемка, июнь 2022",
  "Bird-eye рендеры",
  "Close-up рендеры",
  "Май 2023",
  "Сентябрь 2022",
  "Май 2022",
  "Октябрь 2021",
  "Окрестности",
];

export const carouselimgMob = [
  {
    img: "/video_bg_m.png",
    title: "Аэросъемка, июнь 2022",
  },
  {
    img: "/bird_eye_m_1.png",
    title: "Bird-eye рендеры",
  },
  {
    img: "/bird_eye_m_2.png",
    title: "Bird-eye рендеры",
  },
  {
    img: "/close_up_m_1.png",
    title: "Close-up рендеры",
  },
  {
    img: "/close_up_m_2.png",
    title: "Close-up рендеры",
  },
  {
    img: "/may_m_1_2023.png",
    title: "Май 2023",
  },
  {
    img: "/may_m_2_2023.png",
    title: "Май 2023",
  },
  {
    img: "/sept_m_1_2022.png",
    title: "Сентябрь 2022",
  },
  {
    img: "/sept_m_2_2022.png",
    title: "Сентябрь 2022",
  },
  {
    img: "/mob_g_1.png",
    title: "Май 2022",
  },
  {
    img: "/mob_g_2.png",
    title: "Май 2022",
  },
  {
    img: "/mob_g_3.png",
    title: "Октябрь 2021",
  },
  {
    img: "/mob_g_4.png",
    title: "Октябрь 2021",
  },
  {
    img: "/mob_g_5.png",
    title: "Окрестности",
  },
  {
    img: "/mob_g_6.png",
    title: "Окрестности",
  },
];

export const mainSectionContainer = [
  {
    imgBg: "/main-section.jpeg",
    textColorTop: "Свобода",
    textColorBottom: "Комфорт",
    textTop: "пригорода",
    textBottom: "города",
    btnText: "Записаться на просмотр",
    paragraph:
      "Участки под индивидуальную застройку у Финского залива",
    imgMous: "/mous.svg",
    maousText: "Листайте ниже",
  },
  {
    imgBg: "/mainBg_2.png",
    textColorTop: "Жизнь",
    textColorBottom: "счастье",
    textTop: "пригорода",
    textBottom: "города",
    btnText: "Не пропустить просмотр",
    paragraph:
      "Участки под индивидуальную застройку в живописном районе Москвы",
    imgMous: "/mous.svg",
    maousText: "Листайте сейчас",
  },
  {
    imgBg: "/mainBg_3.png",
    textColorTop: "Радость",
    textColorBottom: "жизнь",
    textTop: "пригорода",
    textBottom: "города",
    btnText: "Посетить сейчас",
    paragraph:
      "Участки под индивидуальную застройку в живописном районе Сибири",
    imgMous: "/mous.svg",
    maousText: "Листайте быстрее",
  },
];

export const lands = [
  {
    id: "3",
    sizeMetr: 1997,
    sizeSot: 19.97,
    price: 5192200,
    occupied: true,
    img: "/genPlan/3.svg",
  },
  {
    id: "4",
    sizeMetr: 2000,
    sizeSot: 20.0,
    price: 5200000,
    occupied: false,
    img: "/genPlan/4.svg",
  },
  {
    id: "5",
    sizeMetr: 2004,
    sizeSot: 20.04,
    price: 0,
    occupied: false,
    img: "/genPlan/5.svg",
  },
  {
    id: "6",
    sizeMetr: 2000,
    sizeSot: 20.0,
    price: 5200000,
    occupied: true,
    img: "/genPlan/6.svg",
  },
  {
    id: "9",
    sizeMetr: 872,
    sizeSot: 8.72,
    price: 0,
    occupied: false,
    img: "/genPlan/9.svg",
  },
  {
    id: "10",
    sizeMetr: 995,
    sizeSot: 9.95,
    price: 0,
    occupied: false,
    img: "/genPlan/10.svg",
  },
  {
    id: "11",
    sizeMetr: 995,
    sizeSot: 9.95,
    price: 0,
    occupied: false,
    img: "/genPlan/11.svg",
  },
  {
    id: "12",
    sizeMetr: 1257,
    sizeSot: 12.57,
    price: 0,
    occupied: false,
    img: "/genPlan/12.svg",
  },
  {
    id: "13",
    sizeMetr: 1645,
    sizeSot: 16.45,
    price: 4441500,
    occupied: false,
    img: "/genPlan/13.svg",
  },
  {
    id: "14",
    sizeMetr: 1328,
    sizeSot: 13.28,
    price: 3585600,
    occupied: false,
    img: "/genPlan/14.svg",
  },
  {
    id: "15",
    sizeMetr: 1079,
    sizeSot: 10.79,
    price: 0,
    occupied: false,
    img: "/genPlan/15.svg",
  },
  {
    id: "16",
    sizeMetr: 987,
    sizeSot: 9.87,
    price: 0,
    occupied: false,
    img: "/genPlan/16.svg",
  },
  {
    id: "17",
    sizeMetr: 989,
    sizeSot: 9.89,
    price: 0,
    occupied: false,
    img: "/genPlan/17.svg",
  },
  {
    id: "18",
    sizeMetr: 1038,
    sizeSot: 10.38,
    price: 2802600,
    occupied: true,
    img: "/genPlan/18.svg",
  },
  {
    id: "19",
    sizeMetr: 1025,
    sizeSot: 10.25,
    price: 0,
    occupied: false,
    img: "/genPlan/19.svg",
  },
  {
    id: "20",
    sizeMetr: 1000,
    sizeSot: 10.0,
    price: 0,
    occupied: false,
    img: "/genPlan/20.svg",
  },
  {
    id: "21",
    sizeMetr: 1000,
    sizeSot: 10.0,
    price: 0,
    occupied: true,
    img: "/genPlan/21.svg",
  },
  {
    id: "22",
    sizeMetr: 1115,
    sizeSot: 11.15,
    price: 0,
    occupied: false,
    img: "/genPlan/22.svg",
  },
  {
    id: "23",
    sizeMetr: 1042,
    sizeSot: 10.42,
    price: 0,
    occupied: false,
    img: "/genPlan/23.svg",
  },
  {
    id: "24",
    sizeMetr: 1051,
    sizeSot: 10.51,
    price: 0,
    occupied: false,
    img: "/genPlan/24.svg",
  },
  {
    id: "25",
    sizeMetr: 1025,
    sizeSot: 10.25,
    price: 0,
    occupied: false,
    img: "/genPlan/25.svg",
  },
  {
    id: "26",
    sizeMetr: 1019,
    sizeSot: 10.19,
    price: 2853200,
    occupied: false,
    img: "/genPlan/26.svg",
  },
  {
    id: "27",
    sizeMetr: 1030,
    sizeSot: 10.30,
    price: 0,
    occupied: false,
    img: "/genPlan/27.svg",
  },
  {
    id: "30",
    sizeMetr: 1061,
    sizeSot: 10.61,
    price: 2970800,
    occupied: false,
    img: "/genPlan/30.svg",
  },
  {
    id: "31",
    sizeMetr: 1055,
    sizeSot: 10.55,
    price: 0,
    occupied: false,
    img: "/genPlan/31.svg",
  },
  {
    id: "32",
    sizeMetr: 1105,
    sizeSot: 11.05,
    price: 0,
    occupied: false,
    img: "/genPlan/32.svg",
  },
  {
    id: "33",
    sizeMetr: 1093,
    sizeSot: 10.93,
    price: 0,
    occupied: false,
    img: "/genPlan/33.svg",
  },
  {
    id: "34",
    sizeMetr: 1161,
    sizeSot: 11.61,
    price: 0,
    occupied: false,
    img: "/genPlan/34.svg",
  },
  {
    id: "35",
    sizeMetr: 1144,
    sizeSot: 11.44,
    price: 0,
    occupied: false,
    img: "/genPlan/35.svg",
  },
  {
    id: "36",
    sizeMetr: 1200,
    sizeSot: 12.0,
    price: 0,
    occupied: false,
    img: "/genPlan/36.svg",
  },
  {
    id: "37",
    sizeMetr: 2215,
    sizeSot: 22.15,
    price: 6202000,
    occupied: false,
    img: "/genPlan/37.svg",
  },
  {
    id: "38",
    sizeMetr: 918,
    sizeSot: 9.18,
    price: 0,
    occupied: false,
    img: "/genPlan/38.svg",
  },
  {
    id: "39",
    sizeMetr: 895,
    sizeSot: 8.95,
    price: 0,
    occupied: false,
    img: "/genPlan/39.svg",
  },
  {
    id: "40",
    sizeMetr: 942,
    sizeSot: 9.42,
    price: 0,
    occupied: false,
    img: "/genPlan/40.svg",
  },
  {
    id: "41",
    sizeMetr: 917,
    sizeSot: 9.17,
    price: 0,
    occupied: false,
    img: "/genPlan/41.svg",
  },
  {
    id: "42",
    sizeMetr: 967,
    sizeSot: 9.67,
    price: 0,
    occupied: false,
    img: "/genPlan/42.svg",
  },
  {
    id: "43",
    sizeMetr: 939,
    sizeSot: 9.39,
    price: 0,
    occupied: false,
    img: "/genPlan/43.svg",
  },
  {
    id: "44",
    sizeMetr: 1303,
    sizeSot: 13.03,
    price: 0,
    occupied: false,
    img: "/genPlan/44.svg",
  },
  {
    id: "45",
    sizeMetr: 1001,
    sizeSot: 10.01,
    price: 0,
    occupied: false,
    img: "/genPlan/45.svg",
  },
  {
    id: "46",
    sizeMetr: 1774,
    sizeSot: 17.74,
    price: 0,
    occupied: false,
    img: "/genPlan/46.svg",
  },
  {
    id: "47",
    sizeMetr: 1614,
    sizeSot: 16.14,
    price: 0,
    occupied: false,
    img: "/genPlan/47.svg",
  },
  {
    id: "48",
    sizeMetr: 1699,
    sizeSot: 16.99,
    price: 0,
    occupied: false,
    img: "/genPlan/48.svg",
  },
  {
    id: "49",
    sizeMetr: 1887,
    sizeSot: 18.87,
    price: 5094900,
    occupied: false,
    img: "/genPlan/49.svg",
  },
  {
    id: "50",
    sizeMetr: 2126,
    sizeSot: 21.26,
    price: 5740200,
    occupied: false,
    img: "/genPlan/50.svg",
  },
  {
    id: "51",
    sizeMetr: 1759,
    sizeSot: 17.59,
    price: 0,
    occupied: false,
    img: "/genPlan/51.svg",
  },
  {
    id: "52",
    sizeMetr: 2417,
    sizeSot: 24.17,
    price: 0,
    occupied: true,
    img: "/genPlan/52.svg",
  },
  {
    id: "53",
    sizeMetr: 1852,
    sizeSot: 18.52,
    price: 0,
    occupied: false,
    img: "/genPlan/53.svg",
  },
  {
    id: "54",
    sizeMetr: 1821,
    sizeSot: 18.21,
    price: 0,
    occupied: false,
    img: "/genPlan/54.svg",
  },
  {
    id: "55",
    sizeMetr: 1430,
    sizeSot: 14.30,
    price: 0,
    occupied: false,
    img: "/genPlan/55.svg",
  },
  {
    id: "56",
    sizeMetr: 1164,
    sizeSot: 11.64,
    price: 3259200,
    occupied: false,
    img: "/genPlan/56.svg",
  },
  {
    id: "57",
    sizeMetr: 1220,
    sizeSot: 12.20,
    price: 3416000,
    occupied: false,
    img: "/genPlan/57.svg",
  },
  {
    id: "58",
    sizeMetr: 1269,
    sizeSot: 12.69,
    price: 3553200,
    occupied: false,
    img: "/genPlan/58.svg",
  },
  {
    id: "60",
    sizeMetr: 1289,
    sizeSot: 12.89,
    price: 3609200,
    occupied: false,
    img: "/genPlan/60.svg",
  },
  {
    id: "61",
    sizeMetr: 1348,
    sizeSot: 13.48,
    price: 0,
    occupied: false,
    img: "/genPlan/61.svg",
  },
  {
    id: "62",
    sizeMetr: 1407,
    sizeSot: 14.07,
    price: 0,
    occupied: false,
    img: "/genPlan/62.svg",
  },
  {
    id: "63",
    sizeMetr: 1466,
    sizeSot: 14.66,
    price: 0,
    occupied: false,
    img: "/genPlan/63.svg",
  },
  {
    id: "64",
    sizeMetr: 1525,
    sizeSot: 15.25,
    price: 4270000,
    occupied: false,
    img: "/genPlan/64.svg",
  },
  {
    id: "65",
    sizeMetr: 1706,
    sizeSot: 17.06,
    price: 4776800,
    occupied: false,
    img: "/genPlan/65.svg",
  },
  {
    id: "66",
    sizeMetr: 906,
    sizeSot: 9.06,
    price: 0,
    occupied: false,
    img: "/genPlan/66.svg",
  },
  {
    id: "67",
    sizeMetr: 1094,
    sizeSot: 10.94,
    price: 0,
    occupied: false,
    img: "/genPlan/67.svg",
  },
  {
    id: "68",
    sizeMetr: 1205,
    sizeSot: 12.05,
    price: 0,
    occupied: false,
    img: "/genPlan/68.svg",
  },
  {
    id: "69",
    sizeMetr: 1151,
    sizeSot: 11.51,
    price: 0,
    occupied: false,
    img: "/genPlan/69.svg",
  },
  {
    id: "70",
    sizeMetr: 1605,
    sizeSot: 16.05,
    price: 4494000,
    occupied: false,
    img: "/genPlan/70.svg",
  },
  {
    id: "71",
    sizeMetr: 1442,
    sizeSot: 14.42,
    price: 0,
    occupied: false,
    img: "/genPlan/71.svg",
  },
  {
    id: "72",
    sizeMetr: 1393,
    sizeSot: 13.93,
    price: 0,
    occupied: false,
    img: "/genPlan/72.svg",
  },
  {
    id: "73",
    sizeMetr: 1343,
    sizeSot: 13.43,
    price: 3760400,
    occupied: false,
    img: "/genPlan/73.svg",
  },
  {
    id: "74",
    sizeMetr: 1294,
    sizeSot: 12.94,
    price: 3623200,
    occupied: false,
    img: "/genPlan/74.svg",
  },
  {
    id: "75",
    sizeMetr: 1245,
    sizeSot: 12.45,
    price: 3486000,
    occupied: false,
    img: "/genPlan/75.svg",
  },
  {
    id: "77",
    sizeMetr: 1243,
    sizeSot: 12.43,
    price: 3480400,
    occupied: false,
    img: "/genPlan/77.svg",
  },
  {
    id: "78",
    sizeMetr: 1206,
    sizeSot: 12.06,
    price: 0,
    occupied: false,
    img: "/genPlan/78.svg",
  },
  {
    id: "79",
    sizeMetr: 1205,
    sizeSot: 12.05,
    price: 3374000,
    occupied: false,
    img: "/genPlan/79.svg",
  },
  {
    id: "80",
    sizeMetr: 1819,
    sizeSot: 18.19,
    price: 4911300,
    occupied: false,
    img: "/genPlan/80.svg",
  },
  {
    id: "81",
    sizeMetr: 1955,
    sizeSot: 19.55,
    price: 0,
    occupied: true,
    img: "/genPlan/81.svg",
  },
  {
    id: "82",
    sizeMetr: 1729,
    sizeSot: 17.29,
    price: 4668300,
    occupied: true,
    img: "/genPlan/82.svg",
  },
  {
    id: "83",
    sizeMetr: 1965,
    sizeSot: 19.65,
    price: 5305500,
    occupied: true,
    img: "/genPlan/83.svg",
  },
  {
    id: "84",
    sizeMetr: 2006,
    sizeSot: 20.06,
    price: 5416200,
    occupied: true,
    img: "/genPlan/84.svg",
  },
  {
    id: "85",
    sizeMetr: 1976,
    sizeSot: 19.76,
    price: 5335200,
    occupied: false,
    img: "/genPlan/85.svg",
  },
  {
    id: "86",
    sizeMetr: 1995,
    sizeSot: 19.95,
    price: 0,
    occupied: false,
    img: "/genPlan/86.svg",
  },
  {
    id: "87",
    sizeMetr: 2027,
    sizeSot: 20.27,
    price: 5472900,
    occupied: false,
    img: "/genPlan/87.svg",
  },
  {
    id: "88",
    sizeMetr: 2124,
    sizeSot: 21.24,
    price: 5734800,
    occupied: false,
    img: "/genPlan/88.svg",
  },
  {
    id: "89",
    sizeMetr: 3264,
    sizeSot: 32.64,
    price: 10444800,
    occupied: true,
    img: "/genPlan/89.svg",
  },
  {
    id: "90",
    sizeMetr: 1849,
    sizeSot: 18.49,
    price: 0,
    occupied: false,
    img: "/genPlan/90.svg",
  },
  {
    id: "91",
    sizeMetr: 2000,
    sizeSot: 20.0,
    price: 0,
    occupied: false,
    img: "/genPlan/91.svg",
  },
  {
    id: "92",
    sizeMetr: 1100,
    sizeSot: 11.0,
    price: 0,
    occupied: false,
    img: "/genPlan/92.svg",
  },
  {
    id: "93",
    sizeMetr: 1945,
    sizeSot: 19.45,
    price: 0,
    occupied: true,
    img: "/genPlan/93.svg",
  },
  {
    id: "94",
    sizeMetr: 2028,
    sizeSot: 20.28,
    price: 0,
    occupied: true,
    img: "/genPlan/94.svg",
  },
  {
    id: "95",
    sizeMetr: 1986,
    sizeSot: 19.86,
    price: 0,
    occupied: true,
    img: "/genPlan/95.svg",
  },
  {
    id: "96",
    sizeMetr: 1960,
    sizeSot: 19.60,
    price: 0,
    occupied: true,
    img: "/genPlan/96.svg",
  },
  {
    id: "97",
    sizeMetr: 2150,
    sizeSot: 21.50,
    price: 0,
    occupied: true,
    img: "/genPlan/97.svg",
  },
  {
    id: "98",
    sizeMetr: 1531,
    sizeSot: 15.31,
    price: 0,
    occupied: true,
    img: "/genPlan/98.svg",
  },
  {
    id: "99",
    sizeMetr: 1845,
    sizeSot: 18.45,
    price: 0,
    occupied: true,
    img: "/genPlan/99.svg",
  },
  {
    id: "100",
    sizeMetr: 1811,
    sizeSot: 18.11,
    price: 0,
    occupied: true,
    img: "/genPlan/100.svg",
  },
  {
    id: "101",
    sizeMetr: 2386,
    sizeSot: 23.86,
    price: 0,
    occupied: true,
    img: "/genPlan/101.svg",
  },
  {
    id: "102",
    sizeMetr: 2432,
    sizeSot: 24.32,
    price: 0,
    occupied: true,
    img: "/genPlan/102.svg",
  },
  {
    id: "103",
    sizeMetr: 2055,
    sizeSot: 20.55,
    price: 0,
    occupied: true,
    img: "/genPlan/103.svg",
  },
  {
    id: "104",
    sizeMetr: 2929,
    sizeSot: 29.29,
    price: 0,
    occupied: true,
    img: "/genPlan/104.svg",
  },
  {
    id: "105",
    sizeMetr: 2233,
    sizeSot: 22.33,
    price: 0,
    occupied: true,
    img: "/genPlan/105.svg",
  },
  {
    id: "106",
    sizeMetr: 2844,
    sizeSot: 28.44,
    price: 0,
    occupied: true,
    img: "/genPlan/106.svg",
  },
  {
    id: "107",
    sizeMetr: 2541,
    sizeSot: 25.41,
    price: 0,
    occupied: true,
    img: "/genPlan/107.svg",
  },
  {
    id: "108",
    sizeMetr: 2045,
    sizeSot: 20.45,
    price: 0,
    occupied: true,
    img: "/genPlan/108.svg",
  },
  {
    id: "109",
    sizeMetr: 2432,
    sizeSot: 24.32,
    price: 0,
    occupied: true,
    img: "/genPlan/109.svg",
  },
  {
    id: "110",
    sizeMetr: 2420,
    sizeSot: 24.20,
    price: 0,
    occupied: true,
    img: "/genPlan/110.svg",
  },
  {
    id: "111",
    sizeMetr: 2147,
    sizeSot: 21.47,
    price: 0,
    occupied: true,
    img: "/genPlan/111.svg",
  },
  {
    id: "112",
    sizeMetr: 1749,
    sizeSot: 17.49,
    price: 0,
    occupied: true,
    img: "/genPlan/112.svg",
  },
  {
    id: "113",
    sizeMetr: 1642,
    sizeSot: 16.42,
    price: 0,
    occupied: true,
    img: "/genPlan/113.svg",
  },
  {
    id: "114",
    sizeMetr: 2698,
    sizeSot: 26.98,
    price: 0,
    occupied: true,
    img: "/genPlan/114.svg",
  },
  {
    id: "115",
    sizeMetr: 2381,
    sizeSot: 23.81,
    price: 0,
    occupied: true,
    img: "/genPlan/115.svg",
  },
  {
    id: "116",
    sizeMetr: 2055,
    sizeSot: 20.55,
    price: 0,
    occupied: true,
    img: "/genPlan/116.svg",
  },
  {
    id: "117",
    sizeMetr: 1727,
    sizeSot: 17.27,
    price: 0,
    occupied: true,
    img: "/genPlan/117.svg",
  },
  {
    id: "118",
    sizeMetr: 1817,
    sizeSot: 18.17,
    price: 0,
    occupied: true,
    img: "/genPlan/118.svg",
  },
];
